installedApps:
  - git
sfdxPluginsStdout: "@salesforce/lwc-dev-mobile \e[2m1.5.2\e[22m\n@salesforce/lwc-dev-server \e[2m2.11.0\e[22m\nsfdmu \e[2m4.17.6\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.5.0\e[22m\nsfdx-hardis \e[2m2.95.2\e[22m\nsfpowerkit \e[2m6.0.0\e[22m\ntexei-sfdx-plugin \e[2m1.17.0\e[22m\n"
