/**
 * @description       : 
 * @author            : ¤ → alessio.marra@nexusat.it
 * @last modified on  : 25/03/2021
 * @last modified by  : ¤ → alessio.marra@nexusat.it
 * Modifications Log 
 * Ver   Date         Author                         Modification
 * 1.0   25/03/2021   ¤ → alessio.marra@nexusat.it   Initial Version
**/
public class ExceptionHandler {

	public class ReferenceNumberException extends Exception {

		// public void ReferenceNumberException() {
		// 	super.ReferenceNumberException();
		// }
		
		// public override String getMessage() {
		// 	return super.getMessage();
		// }
	}
}